### ISSUE TITLE
Can't use on chrome last version

### ISSUE THREAD

**Issue by arckosfr** [RustyBalboadev/MelvorTrainer#2]
It seems chrome don't allow extensions that are not on the store anymore.
Can't install it

**Comment by rustybalboadev** [comment]
The Trainer is now on the Chrome store if you'd rather install it there. [link](https://chrome.google.com/webstore/detail/opfjiinhldoaonbjidlpmjepgladiilp/)

I think your issue was you didn't have Developer Mode on in chrome://extensions
