### ISSUE TITLE
Request: Instakill

### ISSUE THREAD

**Issue by guanhaowu** [RustyBalboadev/MelvorTrainer#3]
Hey Author,

Would it be possible to add instaKill with this line of code? For some reason I couldn't get it to working on my own. It might be due to the workings of add-on in relation to the webpage and its lifecycle (my guess. Not that I have that many knowledge about Chrome apps API).

Here is the line for most instakill:
if (enemyInCombat && combatData.enemy.hitpoints>0){damageEnemy(combatData.enemy.hitpoints);}

**Comment by rustybalboadev** [comment]
I haven't looked at the website since I made this project... I do remember trying to do something with hitpoints and nothing would work. So I'm not really sure Sorry :/

**Comment by guanhaowu** [comment]
Well executing that if statement works in devtools console. Would you be able to point out what i should be looking for in order to make buttons interact with the page to execute lines in the console?

There is another script/addon for firefox, they manage to create instant attack but their script is also made to the page like an extension instead of clicking the add-on to open. For now it seems bit too complex for me to understand how they made that interaction to the webpage.
________________________________

**Comment by rustybalboadev** [comment]
If you're talking about the button on the popup when you click the extension icon. In popup.js i have an event listening for the button click then it runs a function in background.js

**Comment by guanhaowu** [comment]
I've managed to make it work and changed lots of repeated code and partially functioning Mastery unlock feature to unlock 100% using the array of each mastery and changing Mastery level and MasteryXP.
